[package]
name = "oxker"
version = "0.1.5"
edition = "2021"
authors = ["Jack Wills <email@mrjackwills.com>"]
description = "A simple tui to view & control docker containers"
repository = "https://github.com/mrjackwills/oxker"
homepage = "https://github.com/mrjackwills/oxker"
license = "MIT"
readme = "README.md"
keywords = ["docker", "tui", "tokio", "terminal", "podman"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
bollard = "0.13"
cansi = "2.2"
clap={version="4.0", features = ["derive", "unicode", "color"] }
crossterm = "0.25"
futures-util = "0.3"
parking_lot = {version= "0.12"}
tokio = {version = "1.21", features=["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
tui = "0.19"
uuid = {version = "1.1", features = ["v4", "fast-rng"]}

[dev-dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip=true
debug = false


