[package]
name = "oxker"
version = "0.4.1"
edition = "2021"
authors = ["Jack Wills <email@mrjackwills.com>"]
description = "A simple tui to view & control docker containers"
repository = "https://github.com/mrjackwills/oxker"
homepage = "https://github.com/mrjackwills/oxker"
license = "MIT"
readme = "README.md"
keywords = ["docker", "tui", "tokio", "terminal", "podman"]
categories = ["command-line-utilities"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
expect_used = "warn"
nursery = "warn"
pedantic ="warn"
todo = "warn"
unused_async = "warn"
unwrap_used = "warn"
module_name_repetitions = "allow"
doc_markdown = "allow"
similar_names = "allow"

[dependencies]
anyhow = "1.0"
bollard = "0.15"
cansi = "2.2"
clap = { version = "4.4", features = ["derive", "unicode", "color"] }
crossterm = "0.27"
futures-util = "0.3"
parking_lot = { version= "0.12" }
tokio = { version = "1.34", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
ratatui = "0.24"
uuid = { version = "1.6", features = ["v4", "fast-rng"] }
directories = "5.0"

[dev-dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip=true
debug = false

