version: "3.8"
networks:
  oxker-example-net:
    name: oxker-examaple-net
services:
  postgres_but_with_a_longer_container_name:
    container_name: postgres_but_with_a_longer_container_name
    build:
       dockerfile: ./postgres.Dockerfile
       context: "."
    environment: 
      - POSTGRES_PASSWORD=never_use_this_password_in_production
    ipc: private
    restart: always
    shm_size: 256MB
    networks:
         - oxker-example-net
    deploy:
      resources:
        limits:
          memory: 1024M
  redis:
    image: redis:alpine3.19
    container_name: redis
    ipc: private
    restart: always
    networks:
      - oxker-example-net
    deploy:
      resources:
        limits:
          memory: 384M
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ipc: private
    restart: always
    networks:
      - oxker-example-net
    deploy:
      resources:
        limits:
          memory: 512M
