
networks:
  oxker-example-net:
    name: oxker-examaple-net
services:
  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    environment: 
     - POSTGRES_PASSWORD=never_use_this_password_in_production
    ipc: private
    restart: always
    shm_size: 256MB
    networks:
      - oxker-example-net
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "5432:5432"
      - "5433:5433"
      - "5434:5434"
    labels:
      - com.oxker.service=postgres
      - com.oxker.target=development
  redis:
    image: redis:alpine3.19
    container_name: redis
    ipc: private
    restart: always
    networks:
      - oxker-example-net
    deploy:
      resources:
        limits:
          memory: 384M
    ports:
      - "6379:6379"
      - "5422:5422"
    labels:
      - com.oxker.service=redis
      - com.oxker.target=development
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ipc: private
    restart: always
    networks:
      - oxker-example-net
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          memory: 512M
    labels:
      - com.oxker.service=rabbitmq
      - com.oxker.target=development
